/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 22 03:04:23 KST 2017
 */

package com.sleepycat.je.latch;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import com.sleepycat.je.dbi.EnvironmentImpl;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class LatchSupport_ESTest3 extends LatchSupport_ESTest_scaffolding3 {

  @Test
  public void test0()  throws Throwable  {
      Java5LatchImpl java5LatchImpl0 = (Java5LatchImpl)LatchSupport.makeLatch(" parent=", (EnvironmentImpl) null);
      assertNotNull(java5LatchImpl0);
  }


  @Test
  public void test2()  throws Throwable  {
      Java5SharedLatchImpl java5SharedLatchImpl0 = (Java5SharedLatchImpl)LatchSupport.makeSharedLatch(" parent=", (EnvironmentImpl) null);
      assertNotNull(java5SharedLatchImpl0);
  }



  @Test
  public void test5()  throws Throwable  {
      LatchSupport.clearNotes();
  }



  @Test
  public void test8()  throws Throwable  {
      Class class0 = LatchSupport.getJava5LatchClass();
      assertEquals(0, class0.getModifiers());
  }
}
