/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 22 13:52:39 KST 2017
 */

package com.sleepycat.je;

import static org.junit.Assert.assertEquals;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class JEVersion_ESTest2 extends JEVersion_ESTest_scaffolding2 {






}
