/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 21 23:16:56 KST 2017
 */

package com.sleepycat.je;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class DeadlockException_ESTest6 extends DeadlockException_ESTest_scaffolding6 {

  @Test
  public void test0()  throws Throwable  {
      DeadlockException deadlockException0 = new DeadlockException(",N'GP Hk+B>~h");
      DeadlockException deadlockException1 = new DeadlockException((Throwable) deadlockException0);
      assertFalse(deadlockException0.equals((Object)deadlockException1));
  }

  @Test
  public void test1()  throws Throwable  {
      DeadlockException deadlockException0 = new DeadlockException();
      assertEquals("com.sleepycat.je.DeadlockException", deadlockException0.toString());
  }

  @Test
  public void test2()  throws Throwable  {
      DeadlockException deadlockException0 = new DeadlockException(",N'GP Hk+B>~h");
      DeadlockException deadlockException1 = new DeadlockException(",N'GP Hk+B>~h", (Throwable) deadlockException0);
      assertEquals(",N'GP Hk+B>~h", deadlockException1.getMessage());
  }
}
