/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 22 14:44:46 KST 2017
 */

package com.sleepycat.je.latch;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.sleepycat.je.dbi.EnvironmentImpl;
import com.sleepycat.je.latch.LatchException;
import com.sleepycat.je.latch.LatchImpl;
import com.sleepycat.je.latch.LatchNotHeldException;
import com.sleepycat.je.latch.LatchStats;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class LatchImpl_ESTest4 extends LatchImpl_ESTest_scaffolding4 {

  @Test
  public void test01()  throws Throwable  {
      LatchImpl latchImpl0 = new LatchImpl((EnvironmentImpl) null);
      latchImpl0.acquire();
      latchImpl0.release();
      assertEquals(0, latchImpl0.nWaiters());
  }





  @Test
  public void test06()  throws Throwable  {
      LatchImpl latchImpl0 = new LatchImpl((EnvironmentImpl) null);
      latchImpl0.hook422();
      assertEquals(0, latchImpl0.nWaiters());
  }




  @Test
  public void test12()  throws Throwable  {
      LatchImpl latchImpl0 = new LatchImpl((EnvironmentImpl) null);
      LatchStats latchStats0 = latchImpl0.getLatchStats();
      assertEquals(0, latchStats0.nAcquireNoWaitSuccessful);
  }



  @Test
  public void test17()  throws Throwable  {
      LatchImpl latchImpl0 = new LatchImpl(".?b./_", (EnvironmentImpl) null);
      int int0 = latchImpl0.nWaiters();
      assertEquals(0, int0);
  }
}
