/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 21 20:58:28 KST 2017
 */

package com.sleepycat.je.recovery;

import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.nio.ByteBuffer;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import com.sleepycat.je.log.LogEntryType;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class CheckpointStart_ESTest7 extends CheckpointStart_ESTest_scaffolding7 {

  @Test
  public void test00()  throws Throwable  {
      CheckpointStart checkpointStart0 = new CheckpointStart(0L, "");
      int int0 = checkpointStart0.getLogSize();
      assertEquals(20, int0);
  }

  @Test
  public void test01()  throws Throwable  {
      CheckpointStart checkpointStart0 = new CheckpointStart(0L, (String) null);
      assertTrue(checkpointStart0.marshallOutsideWriteLatch());
  }

  @Test
  public void test02()  throws Throwable  {
      CheckpointStart checkpointStart0 = new CheckpointStart();
      // Undeclared exception!
      try { 
        checkpointStart0.writeToLog((ByteBuffer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.sleepycat.je.log.LogUtils", e);
      }
  }

  @Test
  public void test03()  throws Throwable  {
      CheckpointStart checkpointStart0 = new CheckpointStart(255L, "&6.H/3QS=HW^[b,2Stf");
      checkpointStart0.postLogWork(255L);
      assertTrue(checkpointStart0.marshallOutsideWriteLatch());
  }

  @Test
  public void test04()  throws Throwable  {
      CheckpointStart checkpointStart0 = new CheckpointStart(0L, "");
      boolean boolean0 = checkpointStart0.countAsObsoleteWhenLogged();
      assertFalse(boolean0);
  }

  @Test
  public void test05()  throws Throwable  {
      CheckpointStart checkpointStart0 = new CheckpointStart(255L, "&6.H/3QS=HW^[b,2Stf");
      boolean boolean0 = checkpointStart0.logEntryIsTransactional();
      assertFalse(boolean0);
  }

  @Test
  public void test06()  throws Throwable  {
      CheckpointStart checkpointStart0 = new CheckpointStart(255L, "&6.H/3QS=HW^[b,2Stf");
      // Undeclared exception!
      try { 
        checkpointStart0.dumpLog((StringBuffer) null, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.sleepycat.je.recovery.CheckpointStart", e);
      }
  }

  @Test
  public void test07()  throws Throwable  {
      CheckpointStart checkpointStart0 = new CheckpointStart();
      long long0 = checkpointStart0.getTransactionId();
      assertEquals(0L, long0);
  }

  @Test
  public void test08()  throws Throwable  {
      CheckpointStart checkpointStart0 = new CheckpointStart(0L, "");
      boolean boolean0 = checkpointStart0.marshallOutsideWriteLatch();
      assertTrue(boolean0);
  }

  @Test
  public void test09()  throws Throwable  {
      CheckpointStart checkpointStart0 = new CheckpointStart(255L, "&6.H/3QS=HW^[b,2Stf");
      LogEntryType logEntryType0 = checkpointStart0.getLogType();
      assertFalse(logEntryType0.isNodeType());
  }

  @Test
  public void test10()  throws Throwable  {
      CheckpointStart checkpointStart0 = new CheckpointStart(0L, "");
      // Undeclared exception!
      try { 
        checkpointStart0.readFromLog((ByteBuffer) null, (byte) (-69));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.sleepycat.je.log.LogUtils", e);
      }
  }

  @Test
  public void test11()  throws Throwable  {
      CheckpointStart checkpointStart0 = new CheckpointStart();
      // Undeclared exception!
      try { 
        checkpointStart0.getLogSize();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.sleepycat.je.log.LogUtils", e);
      }
  }
}
