/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 21 20:59:38 KST 2017
 */

package com.sleepycat.je.recovery;

import static org.junit.Assert.assertEquals;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class RecoveryInfo_ESTest7 extends RecoveryInfo_ESTest_scaffolding7 {

  @Test
  public void test0()  throws Throwable  {
      RecoveryInfo recoveryInfo0 = new RecoveryInfo();
      assertEquals((-1L), recoveryInfo0.checkpointStartLsn);
      
      recoveryInfo0.checkpointStartLsn = (-1654L);
      String string0 = recoveryInfo0.toString();
      assertEquals("Recovery Info ckptStart=0xffffffff/0xfffff98a ckptEnd=<null> useMaxNodeId=0 useMaxDbId=0 useMaxTxnId=0 numMapINs=0 numOtherINs=0 numBinDeltas=0 numDuplicateINs=0 lnFound=0 lnNotFound=0 lnInserted=0 lnReplaced=0 nRepeatIteratorReads=0", string0);
  }

  @Test
  public void test1()  throws Throwable  {
      RecoveryInfo recoveryInfo0 = new RecoveryInfo();
      recoveryInfo0.numMapINs = 4377;
      String string0 = recoveryInfo0.toString();
      assertEquals("Recovery Info ckptEnd=<null> useMaxNodeId=0 useMaxDbId=0 useMaxTxnId=0 numMapINs=4377 numOtherINs=0 numBinDeltas=0 numDuplicateINs=0 lnFound=0 lnNotFound=0 lnInserted=0 lnReplaced=0 nRepeatIteratorReads=0", string0);
  }

  @Test
  public void test2()  throws Throwable  {
      RecoveryInfo recoveryInfo0 = new RecoveryInfo();
      recoveryInfo0.lnNotFound = (-3117);
      String string0 = recoveryInfo0.toString();
      assertEquals((-1L), recoveryInfo0.partialCheckpointStartLsn);
      assertEquals("Recovery Info ckptEnd=<null> useMaxNodeId=0 useMaxDbId=0 useMaxTxnId=0 numMapINs=0 numOtherINs=0 numBinDeltas=0 numDuplicateINs=0 lnFound=0 lnNotFound=-3117 lnInserted=0 lnReplaced=0 nRepeatIteratorReads=0", string0);
  }

  @Test
  public void test3()  throws Throwable  {
      RecoveryInfo recoveryInfo0 = new RecoveryInfo();
      recoveryInfo0.numOtherINs = 391;
      String string0 = recoveryInfo0.toString();
      assertEquals((-1L), recoveryInfo0.partialCheckpointStartLsn);
      assertEquals("Recovery Info ckptEnd=<null> useMaxNodeId=0 useMaxDbId=0 useMaxTxnId=0 numMapINs=0 numOtherINs=391 numBinDeltas=0 numDuplicateINs=0 lnFound=0 lnNotFound=0 lnInserted=0 lnReplaced=0 nRepeatIteratorReads=0", string0);
  }

  @Test
  public void test4()  throws Throwable  {
      RecoveryInfo recoveryInfo0 = new RecoveryInfo();
      recoveryInfo0.useMaxDbId = 834;
      String string0 = recoveryInfo0.toString();
      assertEquals("Recovery Info ckptEnd=<null> useMaxNodeId=0 useMaxDbId=834 useMaxTxnId=0 numMapINs=0 numOtherINs=0 numBinDeltas=0 numDuplicateINs=0 lnFound=0 lnNotFound=0 lnInserted=0 lnReplaced=0 nRepeatIteratorReads=0", string0);
      assertEquals((-1L), recoveryInfo0.partialCheckpointStartLsn);
  }

  @Test
  public void test5()  throws Throwable  {
      RecoveryInfo recoveryInfo0 = new RecoveryInfo();
      recoveryInfo0.useMaxNodeId = 272L;
      String string0 = recoveryInfo0.toString();
      assertEquals((-1L), recoveryInfo0.partialCheckpointStartLsn);
      assertEquals("Recovery Info ckptEnd=<null> useMaxNodeId=272 useMaxDbId=0 useMaxTxnId=0 numMapINs=0 numOtherINs=0 numBinDeltas=0 numDuplicateINs=0 lnFound=0 lnNotFound=0 lnInserted=0 lnReplaced=0 nRepeatIteratorReads=0", string0);
  }

  @Test
  public void test6()  throws Throwable  {
      RecoveryInfo recoveryInfo0 = new RecoveryInfo();
      assertEquals((-1L), recoveryInfo0.lastUsedLsn);
      
      recoveryInfo0.lastUsedLsn = 919L;
      String string0 = recoveryInfo0.toString();
      assertEquals("Recovery Info lastUsed=0x0/0x397 ckptEnd=<null> useMaxNodeId=0 useMaxDbId=0 useMaxTxnId=0 numMapINs=0 numOtherINs=0 numBinDeltas=0 numDuplicateINs=0 lnFound=0 lnNotFound=0 lnInserted=0 lnReplaced=0 nRepeatIteratorReads=0", string0);
  }

  @Test
  public void test7()  throws Throwable  {
      RecoveryInfo recoveryInfo0 = new RecoveryInfo();
      assertEquals((-1L), recoveryInfo0.nextAvailableLsn);
      
      recoveryInfo0.nextAvailableLsn = 0L;
      String string0 = recoveryInfo0.toString();
      assertEquals("Recovery Info nextAvail=0x0/0x0 ckptEnd=<null> useMaxNodeId=0 useMaxDbId=0 useMaxTxnId=0 numMapINs=0 numOtherINs=0 numBinDeltas=0 numDuplicateINs=0 lnFound=0 lnNotFound=0 lnInserted=0 lnReplaced=0 nRepeatIteratorReads=0", string0);
  }

  @Test
  public void test8()  throws Throwable  {
      RecoveryInfo recoveryInfo0 = new RecoveryInfo();
      assertEquals((-1L), recoveryInfo0.checkpointEndLsn);
      
      recoveryInfo0.checkpointEndLsn = 688L;
      String string0 = recoveryInfo0.toString();
      assertEquals("Recovery Info ckptEnd=0x0/0x2b0 ckptEnd=<null> useMaxNodeId=0 useMaxDbId=0 useMaxTxnId=0 numMapINs=0 numOtherINs=0 numBinDeltas=0 numDuplicateINs=0 lnFound=0 lnNotFound=0 lnInserted=0 lnReplaced=0 nRepeatIteratorReads=0", string0);
  }
}
