/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 22 01:04:12 KST 2017
 */

package com.sleepycat.je.log;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.fail;

import java.io.File;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class JEFileFilter_ESTest6 extends JEFileFilter_ESTest_scaffolding6 {

  @Test
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[4];
      JEFileFilter jEFileFilter0 = new JEFileFilter(stringArray0);
      boolean boolean0 = jEFileFilter0.accept((File) null, "VN_~$lC!p$?s.Gm");
      assertFalse(boolean0);
  }

  @Test
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[8];
      JEFileFilter jEFileFilter0 = new JEFileFilter(stringArray0);
      boolean boolean0 = jEFileFilter0.accept((File) null, ".lq]");
      assertFalse(boolean0);
  }

  @Test
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[0];
      JEFileFilter jEFileFilter0 = new JEFileFilter(stringArray0);
      // Undeclared exception!
      try { 
        jEFileFilter0.accept((File) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test
  public void test3()  throws Throwable  {
      String[] stringArray0 = new String[13];
      JEFileFilter jEFileFilter0 = new JEFileFilter(stringArray0);
      boolean boolean0 = jEFileFilter0.accept((File) null, "a.nS8<}<.'Dz@yavK");
      assertFalse(boolean0);
  }

  @Test
  public void test4()  throws Throwable  {
      String[] stringArray0 = new String[8];
      stringArray0[4] = ".lq]";
      JEFileFilter jEFileFilter0 = new JEFileFilter(stringArray0);
      boolean boolean0 = jEFileFilter0.accept((File) null, "}z<q2^%.lq]");
      assertFalse(boolean0);
  }

  @Test
  public void test5()  throws Throwable  {
      String[] stringArray0 = new String[8];
      JEFileFilter jEFileFilter0 = new JEFileFilter(stringArray0);
      boolean boolean0 = jEFileFilter0.accept((File) null, "}z<q2^%.lq]");
      assertFalse(boolean0);
  }

  @Test
  public void test6()  throws Throwable  {
      String[] stringArray0 = new String[26];
      JEFileFilter jEFileFilter0 = new JEFileFilter(stringArray0);
      boolean boolean0 = jEFileFilter0.accept((File) null, "a.nb.<1}<8.'DzaNvK_");
      assertFalse(boolean0);
  }
}
