/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 21 19:55:34 KST 2017
 */

package com.sleepycat.je.config;

import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class BooleanConfigParam_ESTest7 extends BooleanConfigParam_ESTest_scaffolding7 {

  @Test
  public void test0()  throws Throwable  {
      BooleanConfigParam booleanConfigParam0 = new BooleanConfigParam("XXBYH)O7KTDC>J5|Z39", false, true, "XXBYH)O7KTDC>J5|Z39");
      // Undeclared exception!
      try { 
        booleanConfigParam0.validateValue((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.sleepycat.je.config.BooleanConfigParam", e);
      }
  }

  @Test
  public void test1()  throws Throwable  {
      BooleanConfigParam booleanConfigParam0 = null;
      try {
        booleanConfigParam0 = new BooleanConfigParam("", false, false, "");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         //  A configuration parameter name can't be null or 0 length
         //
         assertThrownBy("com.sleepycat.je.config.ConfigParam", e);
      }
  }

  @Test
  public void test2()  throws Throwable  {
      BooleanConfigParam booleanConfigParam0 = new BooleanConfigParam("Z&C^9'`3/>1*RN", true, true, "");
      booleanConfigParam0.validateValue("true");
      assertNull(booleanConfigParam0.getExtraDescription());
  }

  @Test
  public void test3()  throws Throwable  {
      BooleanConfigParam booleanConfigParam0 = new BooleanConfigParam(": ", true, true, "false");
      try { 
        booleanConfigParam0.validateValue(": ");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // com.sleepycat.je.config.BooleanConfigParam: :  not valid boolean : 
         //
         assertThrownBy("com.sleepycat.je.config.BooleanConfigParam", e);
      }
  }

  @Test
  public void test4()  throws Throwable  {
      BooleanConfigParam booleanConfigParam0 = new BooleanConfigParam(": ", true, true, "false");
      booleanConfigParam0.validateValue("false");
      assertNull(booleanConfigParam0.getExtraDescription());
  }
}
