/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 22 00:49:41 KST 2017
 */

package com.sleepycat.je.latch;

import static org.junit.Assert.assertEquals;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class LatchNotHeldException_ESTest6 extends LatchNotHeldException_ESTest_scaffolding6 {

  @Test
  public void test0()  throws Throwable  {
      LatchNotHeldException latchNotHeldException0 = new LatchNotHeldException(".");
      assertEquals("com.sleepycat.je.latch.LatchNotHeldException: .", latchNotHeldException0.toString());
  }

  @Test
  public void test1()  throws Throwable  {
      LatchNotHeldException latchNotHeldException0 = new LatchNotHeldException();
      assertEquals("com.sleepycat.je.latch.LatchNotHeldException", latchNotHeldException0.toString());
  }
}
