/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 21 23:13:23 KST 2017
 */

package com.sleepycat.je;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class DatabaseException_ESTest6 extends DatabaseException_ESTest_scaffolding6 {

  @Test
  public void test0()  throws Throwable  {
      DatabaseException databaseException0 = new DatabaseException("?(j__2I+iV");
      DatabaseException databaseException1 = new DatabaseException((Throwable) databaseException0);
      assertFalse(databaseException1.equals((Object)databaseException0));
  }

  @Test
  public void test1()  throws Throwable  {
      DatabaseException databaseException0 = new DatabaseException();
      assertEquals("com.sleepycat.je.DatabaseException", databaseException0.toString());
  }

  @Test
  public void test2()  throws Throwable  {
      DatabaseException databaseException0 = new DatabaseException("?(j__2I+iV");
      DatabaseException databaseException1 = new DatabaseException("~SY", (Throwable) databaseException0);
      assertEquals("com.sleepycat.je.DatabaseException: ~SY", databaseException1.toString());
  }
}
