/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 21 23:59:11 KST 2017
 */

package com.sleepycat.je.config;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.sleepycat.je.config.BooleanConfigParam;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class BooleanConfigParam_ESTest6 extends BooleanConfigParam_ESTest_scaffolding6 {

  @Test
  public void test0()  throws Throwable  {
      BooleanConfigParam booleanConfigParam0 = new BooleanConfigParam("9f) Ro2upj1X", false, false, "-89.bim69{,_t r");
      // Undeclared exception!
      try { 
        booleanConfigParam0.validateValue((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.sleepycat.je.config.BooleanConfigParam", e);
      }
  }

  @Test
  public void test1()  throws Throwable  {
      BooleanConfigParam booleanConfigParam0 = null;
      try {
        booleanConfigParam0 = new BooleanConfigParam("", true, false, "");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         //  A configuration parameter name can't be null or 0 length
         //
         assertThrownBy("com.sleepycat.je.config.ConfigParam", e);
      }
  }

  @Test
  public void test2()  throws Throwable  {
      BooleanConfigParam booleanConfigParam0 = new BooleanConfigParam("W*G34}xlXFy\"7", false, false, ": ");
      booleanConfigParam0.validateValue("false");
      assertEquals("false", booleanConfigParam0.getDefault());
  }

  @Test
  public void test3()  throws Throwable  {
      BooleanConfigParam booleanConfigParam0 = new BooleanConfigParam("LX%oz& jb,XH", false, true, "&>8Mk,PBv1e3?&# b&");
      try { 
        booleanConfigParam0.validateValue("&>8Mk,PBv1e3?&# b&");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // com.sleepycat.je.config.BooleanConfigParam: &>8Mk,PBv1e3?&# b& not valid boolean LX%oz& jb,XH
         //
         assertThrownBy("com.sleepycat.je.config.BooleanConfigParam", e);
      }
  }

  @Test
  public void test4()  throws Throwable  {
      BooleanConfigParam booleanConfigParam0 = new BooleanConfigParam("LX%oz& jb,XH", false, true, "&>8Mk,PBv1e3?&# b&");
      booleanConfigParam0.validateValue("true");
      assertEquals("false", booleanConfigParam0.getDefault());
  }
}
