/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 21 20:24:34 KST 2017
 */

package com.sleepycat.je.log;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import java.io.RandomAccessFile;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import com.sleepycat.je.dbi.EnvironmentImpl;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class FileHandle_ESTest7 extends FileHandle_ESTest_scaffolding7 {

  @Test
  public void test0()  throws Throwable  {
      FileHandle fileHandle0 = new FileHandle((RandomAccessFile) null, "'!Pk2<g", (EnvironmentImpl) null, true);
      boolean boolean0 = fileHandle0.isOldHeaderVersion();
      assertTrue(boolean0);
  }

  @Test
  public void test1()  throws Throwable  {
      FileHandle fileHandle0 = new FileHandle((RandomAccessFile) null, "xb{N", (EnvironmentImpl) null, false);
      fileHandle0.hook444("xb{N", (EnvironmentImpl) null);
  }

  @Test
  public void test2()  throws Throwable  {
      FileHandle fileHandle0 = new FileHandle((RandomAccessFile) null, "xb{N", (EnvironmentImpl) null, false);
      fileHandle0.close();
  }

  @Test
  public void test3()  throws Throwable  {
      FileHandle fileHandle0 = new FileHandle((RandomAccessFile) null, "xb{N", (EnvironmentImpl) null, false);
      boolean boolean0 = fileHandle0.isOldHeaderVersion();
      assertFalse(boolean0);
  }

  @Test
  public void test4()  throws Throwable  {
      FileHandle fileHandle0 = new FileHandle((RandomAccessFile) null, "'!Pk2<g", (EnvironmentImpl) null, true);
      RandomAccessFile randomAccessFile0 = fileHandle0.getFile();
      assertNull(randomAccessFile0);
  }
}
