/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 22 02:47:37 KST 2017
 */

package com.sleepycat.je.utilint;

import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import com.sleepycat.je.tree.BIN;
import com.sleepycat.je.tree.IN;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true) 
public class LevelOrderedINMap_ESTest10 extends LevelOrderedINMap_ESTest_scaffolding10 {


  @Test
  public void test1()  throws Throwable  {
      LevelOrderedINMap levelOrderedINMap0 = new LevelOrderedINMap();
      levelOrderedINMap0.put("", levelOrderedINMap0);
      BIN bIN0 = new BIN();
      // Undeclared exception!
      try { 
        levelOrderedINMap0.putIN(bIN0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to java.lang.Integer
         //
         assertThrownBy("java.lang.Integer", e);
      }
  }

  @Test
  public void test2()  throws Throwable  {
      LevelOrderedINMap levelOrderedINMap0 = new LevelOrderedINMap();
      BIN bIN0 = new BIN();
      levelOrderedINMap0.putIN(bIN0);
      levelOrderedINMap0.putIN(bIN0);
      assertFalse(bIN0.isRoot());
  }
}
