/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 22 14:43:21 KST 2017
 */

package com.sleepycat.je.latch;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.sleepycat.je.dbi.EnvironmentImpl;
import com.sleepycat.je.latch.Java5LatchImpl;
import com.sleepycat.je.latch.LatchException;
import com.sleepycat.je.latch.LatchImpl;
import com.sleepycat.je.latch.LatchNotHeldException;
import com.sleepycat.je.latch.LatchStats;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class Latch_ESTest4 extends Latch_ESTest_scaffolding4 {


  @Test
  public void test01()  throws Throwable  {
      LatchImpl latchImpl0 = new LatchImpl((EnvironmentImpl) null);
      latchImpl0.acquire();
      assertTrue(latchImpl0.isOwner());
  }


  @Test
  public void test03()  throws Throwable  {
      LatchImpl latchImpl0 = new LatchImpl((EnvironmentImpl) null);
      latchImpl0.setName("");
      assertFalse(latchImpl0.isOwner());
  }





  @Test
  public void test08()  throws Throwable  {
      Java5LatchImpl java5LatchImpl0 = new Java5LatchImpl();
      LatchStats latchStats0 = java5LatchImpl0.getLatchStats();
      assertEquals(0, latchStats0.nAcquiresUpgrade);
  }

  @Test
  public void test09()  throws Throwable  {
      LatchImpl latchImpl0 = new LatchImpl("", (EnvironmentImpl) null);
      try { 
        latchImpl0.release();
        fail("Expecting exception: LatchNotHeldException");
      
      } catch(LatchNotHeldException e) {
         //
         // LatchImpl() not held
         //
         assertThrownBy("com.sleepycat.je.latch.LatchImpl", e);
      }
  }

  @Test
  public void test10()  throws Throwable  {
      LatchImpl latchImpl0 = new LatchImpl("com.sleepycat.je.latch.Java5LatchImpl$JEReentrantLock@564debb5[Locked by thread TEST_EXECUTION_THREAD_0]", (EnvironmentImpl) null);
      latchImpl0.acquireNoWait();
      try { 
        latchImpl0.acquireNoWait();
        fail("Expecting exception: LatchException");
      
      } catch(LatchException e) {
         //
         // LatchImpl(com.sleepycat.je.latch.Java5LatchImpl$JEReentrantLock@564debb5[Locked by thread TEST_EXECUTION_THREAD_0]) already held
         //
         assertThrownBy("com.sleepycat.je.latch.LatchImpl", e);
      }
  }

  @Test
  public void test11()  throws Throwable  {
      Java5LatchImpl java5LatchImpl0 = new Java5LatchImpl();
      java5LatchImpl0.acquireNoWait();
      java5LatchImpl0.release();
      java5LatchImpl0.acquireNoWait();
      try { 
        java5LatchImpl0.acquire();
        fail("Expecting exception: LatchException");
      
      } catch(LatchException e) {
         //
         // null already held
         //
         assertThrownBy("com.sleepycat.je.latch.Java5LatchImpl", e);
      }
  }
}
