/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 22 02:25:32 KST 2017
 */

package com.sleepycat.je.txn;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import com.sleepycat.je.log.LogEntryType;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true) 
public class TxnCommit_ESTest10 extends TxnCommit_ESTest_scaffolding10 {



  @Test
  public void test2()  throws Throwable  {
      TxnCommit txnCommit0 = new TxnCommit((-65L), (-65L));
      assertEquals((-65L), txnCommit0.getTransactionId());
  }
}
