/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 22 17:09:04 KST 2017
 */

package com.sleepycat.util;

import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class RuntimeExceptionWrapper_ESTest4 extends RuntimeExceptionWrapper_ESTest_scaffolding4 {

}
