/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 21 22:51:56 KST 2017
 */

package com.sleepycat.bind.tuple;

import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import com.sleepycat.je.DatabaseEntry;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class FloatBinding_ESTest6 extends FloatBinding_ESTest_scaffolding6 {

  @Test
  public void test00()  throws Throwable  {
      DatabaseEntry databaseEntry0 = new DatabaseEntry();
      FloatBinding.floatToEntry(45.633793F, databaseEntry0);
      float float0 = FloatBinding.entryToFloat(databaseEntry0);
      assertEquals(45.633793F, float0, 0.01F);
  }

  @Test
  public void test01()  throws Throwable  {
      byte[] byteArray0 = new byte[7];
      byteArray0[0] = (byte) (-103);
      DatabaseEntry databaseEntry0 = new DatabaseEntry(byteArray0);
      float float0 = FloatBinding.entryToFloat(databaseEntry0);
      assertEquals((-6.617445E-24F), float0, 0.01F);
  }

  @Test
  public void test02()  throws Throwable  {
      FloatBinding floatBinding0 = new FloatBinding();
      TupleOutput tupleOutput0 = TupleBase.newOutput();
      // Undeclared exception!
      try { 
        floatBinding0.objectToEntry((Object) null, tupleOutput0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.sleepycat.bind.tuple.FloatBinding", e);
      }
  }

  @Test
  public void test03()  throws Throwable  {
      FloatBinding floatBinding0 = new FloatBinding();
      Byte byte0 = new Byte((byte) (-1));
      TupleOutput tupleOutput0 = floatBinding0.getTupleOutput(byte0);
      // Undeclared exception!
      try { 
        floatBinding0.objectToEntry((Object) floatBinding0, tupleOutput0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // com.sleepycat.bind.tuple.FloatBinding cannot be cast to java.lang.Number
         //
         assertThrownBy("com.sleepycat.bind.tuple.FloatBinding", e);
      }
  }

  @Test
  public void test04()  throws Throwable  {
      FloatBinding floatBinding0 = new FloatBinding();
      Float float0 = new Float((-1327.9832F));
      TupleOutput tupleOutput0 = floatBinding0.getTupleOutput(floatBinding0);
      tupleOutput0.addSize(687);
      // Undeclared exception!
      try { 
        floatBinding0.objectToEntry((Object) float0, tupleOutput0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.lang.System", e);
      }
  }

  @Test
  public void test05()  throws Throwable  {
      // Undeclared exception!
      try { 
        FloatBinding.floatToEntry((-1.0F), (DatabaseEntry) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.sleepycat.bind.tuple.TupleBase", e);
      }
  }

  @Test
  public void test06()  throws Throwable  {
      FloatBinding floatBinding0 = new FloatBinding();
      // Undeclared exception!
      try { 
        floatBinding0.entryToObject((TupleInput) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.sleepycat.bind.tuple.FloatBinding", e);
      }
  }

  @Test
  public void test07()  throws Throwable  {
      FloatBinding floatBinding0 = new FloatBinding();
      byte[] byteArray0 = new byte[0];
      TupleInput tupleInput0 = new TupleInput(byteArray0);
      // Undeclared exception!
      try { 
        floatBinding0.entryToObject(tupleInput0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.sleepycat.bind.tuple.TupleInput", e);
      }
  }

  @Test
  public void test08()  throws Throwable  {
      FloatBinding floatBinding0 = new FloatBinding();
      byte[] byteArray0 = new byte[8];
      TupleInput tupleInput0 = new TupleInput(byteArray0, (-1069), (int) (byte)8);
      // Undeclared exception!
      try { 
        floatBinding0.entryToObject(tupleInput0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1069
         //
         assertThrownBy("com.sleepycat.util.FastInputStream", e);
      }
  }

  @Test
  public void test09()  throws Throwable  {
      // Undeclared exception!
      try { 
        FloatBinding.entryToFloat((DatabaseEntry) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.sleepycat.bind.tuple.TupleBase", e);
      }
  }

  @Test
  public void test10()  throws Throwable  {
      byte[] byteArray0 = new byte[5];
      DatabaseEntry databaseEntry0 = new DatabaseEntry(byteArray0, 16, 390);
      // Undeclared exception!
      try { 
        FloatBinding.entryToFloat(databaseEntry0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 16
         //
         assertThrownBy("com.sleepycat.util.FastInputStream", e);
      }
  }

  @Test
  public void test11()  throws Throwable  {
      DatabaseEntry databaseEntry0 = new DatabaseEntry();
      FloatBinding.floatToEntry(0.0F, databaseEntry0);
      float float0 = FloatBinding.entryToFloat(databaseEntry0);
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test
  public void test12()  throws Throwable  {
      DatabaseEntry databaseEntry0 = new DatabaseEntry();
      // Undeclared exception!
      try { 
        FloatBinding.entryToFloat(databaseEntry0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.sleepycat.bind.tuple.TupleInput", e);
      }
  }

  @Test
  public void test13()  throws Throwable  {
      FloatBinding floatBinding0 = new FloatBinding();
      byte[] byteArray0 = new byte[7];
      TupleInput tupleInput0 = new TupleInput(byteArray0);
      Float float0 = (Float)floatBinding0.entryToObject(tupleInput0);
      assertEquals(0.0F, (float)float0, 0.01F);
  }

  @Test
  public void test14()  throws Throwable  {
      FloatBinding floatBinding0 = new FloatBinding();
      Float float0 = new Float((-1327.9832F));
      TupleOutput tupleOutput0 = floatBinding0.getTupleOutput(floatBinding0);
      floatBinding0.objectToEntry((Object) float0, tupleOutput0);
      assertEquals(4, tupleOutput0.getBufferLength());
  }
}
