/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 21 22:52:41 KST 2017
 */

package com.sleepycat.bind.tuple;

import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import com.sleepycat.je.DatabaseEntry;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class IntegerBinding_ESTest6 extends IntegerBinding_ESTest_scaffolding6 {

  @Test
  public void test00()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      byteArray0[0] = (byte) (-13);
      DatabaseEntry databaseEntry0 = new DatabaseEntry(byteArray0);
      int int0 = IntegerBinding.entryToInt(databaseEntry0);
      assertEquals(1929379840, int0);
  }

  @Test
  public void test01()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      DatabaseEntry databaseEntry0 = new DatabaseEntry(byteArray0);
      int int0 = IntegerBinding.entryToInt(databaseEntry0);
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test
  public void test02()  throws Throwable  {
      byte[] byteArray0 = new byte[20];
      IntegerBinding integerBinding0 = new IntegerBinding();
      TupleInput tupleInput0 = new TupleInput(byteArray0);
      Integer integer0 = (Integer)integerBinding0.entryToObject(tupleInput0);
      assertEquals(Integer.MIN_VALUE, (int)integer0);
  }

  @Test
  public void test03()  throws Throwable  {
      byte[] byteArray0 = new byte[5];
      IntegerBinding integerBinding0 = new IntegerBinding();
      // Undeclared exception!
      try { 
        integerBinding0.objectToEntry((Object) byteArray0[0], (TupleOutput) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.sleepycat.bind.tuple.IntegerBinding", e);
      }
  }

  @Test
  public void test04()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      IntegerBinding integerBinding0 = new IntegerBinding();
      TupleOutput tupleOutput0 = TupleBase.newOutput(byteArray0);
      // Undeclared exception!
      try { 
        integerBinding0.objectToEntry((Object) byteArray0, tupleOutput0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // [B cannot be cast to java.lang.Number
         //
         assertThrownBy("com.sleepycat.bind.tuple.IntegerBinding", e);
      }
  }

  @Test
  public void test05()  throws Throwable  {
      IntegerBinding integerBinding0 = new IntegerBinding();
      Long long0 = new Long((-551L));
      TupleOutput tupleOutput0 = integerBinding0.getTupleOutput(long0);
      tupleOutput0.addSize((-1707));
      // Undeclared exception!
      try { 
        integerBinding0.objectToEntry((Object) long0, tupleOutput0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1707
         //
         assertThrownBy("com.sleepycat.util.FastOutputStream", e);
      }
  }

  @Test
  public void test06()  throws Throwable  {
      // Undeclared exception!
      try { 
        IntegerBinding.intToEntry(0, (DatabaseEntry) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.sleepycat.bind.tuple.TupleBase", e);
      }
  }

  @Test
  public void test07()  throws Throwable  {
      IntegerBinding integerBinding0 = new IntegerBinding();
      Double double0 = new Double((double) 0);
      TupleOutput tupleOutput0 = integerBinding0.getTupleOutput(double0);
      TupleInput tupleInput0 = new TupleInput(tupleOutput0);
      // Undeclared exception!
      try { 
        integerBinding0.entryToObject(tupleInput0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.sleepycat.bind.tuple.TupleInput", e);
      }
  }

  @Test
  public void test08()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      IntegerBinding integerBinding0 = new IntegerBinding();
      TupleInput tupleInput0 = new TupleInput(byteArray0, (-1796), 0);
      // Undeclared exception!
      try { 
        integerBinding0.entryToObject(tupleInput0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1796
         //
         assertThrownBy("com.sleepycat.util.FastInputStream", e);
      }
  }

  @Test
  public void test09()  throws Throwable  {
      // Undeclared exception!
      try { 
        IntegerBinding.entryToInt((DatabaseEntry) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.sleepycat.bind.tuple.TupleBase", e);
      }
  }

  @Test
  public void test10()  throws Throwable  {
      DatabaseEntry databaseEntry0 = new DatabaseEntry();
      byte[] byteArray0 = new byte[0];
      databaseEntry0.setData(byteArray0, 2091, 4747);
      // Undeclared exception!
      try { 
        IntegerBinding.entryToInt(databaseEntry0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2091
         //
         assertThrownBy("com.sleepycat.util.FastInputStream", e);
      }
  }

  @Test
  public void test11()  throws Throwable  {
      byte[] byteArray0 = new byte[2];
      DatabaseEntry databaseEntry0 = new DatabaseEntry(byteArray0, 0, (int) (byte) (-119));
      // Undeclared exception!
      try { 
        IntegerBinding.entryToInt(databaseEntry0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.sleepycat.bind.tuple.TupleInput", e);
      }
  }

  @Test
  public void test12()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      DatabaseEntry databaseEntry0 = new DatabaseEntry(byteArray0);
      IntegerBinding integerBinding0 = new IntegerBinding();
      TupleOutput tupleOutput0 = integerBinding0.getTupleOutput(databaseEntry0);
      Long long0 = new Long((long) (byte)1);
      integerBinding0.objectToEntry((Object) long0, tupleOutput0);
      assertEquals(0, tupleOutput0.getBufferOffset());
  }

  @Test
  public void test13()  throws Throwable  {
      byte[] byteArray0 = new byte[2];
      DatabaseEntry databaseEntry0 = new DatabaseEntry(byteArray0, 0, (int) (byte) (-119));
      IntegerBinding.intToEntry(0, databaseEntry0);
      int int0 = IntegerBinding.entryToInt(databaseEntry0);
      assertEquals(0, int0);
  }

  @Test
  public void test14()  throws Throwable  {
      IntegerBinding integerBinding0 = new IntegerBinding();
      // Undeclared exception!
      try { 
        integerBinding0.entryToObject((TupleInput) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.sleepycat.bind.tuple.IntegerBinding", e);
      }
  }
}
