/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 22 14:24:24 KST 2017
 */

package com.sleepycat.je.dbi;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.sleepycat.je.EnvironmentConfig;
import com.sleepycat.je.dbi.DbEnvPool;
import com.sleepycat.je.dbi.EnvironmentImpl;
import java.io.File;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class DbEnvPool_ESTest4 extends DbEnvPool_ESTest_scaffolding4 {

  @Test
  public void test0()  throws Throwable  {
      DbEnvPool dbEnvPool0 = DbEnvPool.getInstance();
      File file0 = null;
      // Undeclared exception!
      try { 
        dbEnvPool0.getExistingEnvironment((File) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.sleepycat.je.dbi.DbEnvPool", e);
      }
  }




}
