/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 22 00:39:48 KST 2017
 */

package com.sleepycat.je.dbi;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class PutMode_ESTest6 extends PutMode_ESTest_scaffolding6 {

  @Test
  public void test0()  throws Throwable  {
      PutMode putMode0 = new PutMode();
  }
}
