/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 22 03:04:36 KST 2017
 */

package com.sleepycat.je.latch;

import static org.junit.Assert.assertEquals;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class LatchNotHeldException_ESTest3 extends LatchNotHeldException_ESTest_scaffolding3 {


}
