/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 21 21:12:51 KST 2017
 */

package com.sleepycat.je.tree;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import com.sleepycat.je.dbi.DatabaseId;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class DBINReference_ESTest7 extends DBINReference_ESTest_scaffolding7 {

  @Test
  public void test0()  throws Throwable  {
      byte[] byteArray0 = new byte[14];
      DatabaseId databaseId0 = new DatabaseId();
      DBINReference dBINReference0 = new DBINReference((-1L), databaseId0, byteArray0, byteArray0);
      byte[] byteArray1 = dBINReference0.getKey();
      assertSame(byteArray0, byteArray1);
  }

  @Test
  public void test1()  throws Throwable  {
      DatabaseId databaseId0 = new DatabaseId((-418));
      byte[] byteArray0 = new byte[0];
      DBINReference dBINReference0 = new DBINReference(1900L, databaseId0, byteArray0, byteArray0);
      byte[] byteArray1 = dBINReference0.getKey();
      assertArrayEquals(new byte[] {}, byteArray1);
  }

  @Test
  public void test2()  throws Throwable  {
      DatabaseId databaseId0 = new DatabaseId();
      byte[] byteArray0 = new byte[4];
      DBINReference dBINReference0 = new DBINReference((-922L), databaseId0, (byte[]) null, byteArray0);
      byte[] byteArray1 = dBINReference0.getData();
      assertNull(byteArray1);
  }

  @Test
  public void test3()  throws Throwable  {
      DatabaseId databaseId0 = new DatabaseId();
      byte[] byteArray0 = new byte[1];
      DBINReference dBINReference0 = new DBINReference((-894L), databaseId0, byteArray0, byteArray0);
      byte[] byteArray1 = dBINReference0.getData();
      assertSame(byteArray1, byteArray0);
  }

  @Test
  public void test4()  throws Throwable  {
      DatabaseId databaseId0 = new DatabaseId();
      byte[] byteArray0 = new byte[0];
      DBINReference dBINReference0 = new DBINReference((-2072L), databaseId0, byteArray0, byteArray0);
      byte[] byteArray1 = dBINReference0.getData();
      assertSame(byteArray0, byteArray1);
  }

  @Test
  public void test5()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      DBINReference dBINReference0 = new DBINReference((-30L), (DatabaseId) null, byteArray0, (byte[]) null);
      byte[] byteArray1 = dBINReference0.getKey();
      assertNull(byteArray1);
  }

  @Test
  public void test6()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      DBINReference dBINReference0 = new DBINReference((-30L), (DatabaseId) null, byteArray0, (byte[]) null);
      String string0 = dBINReference0.toString();
      assertEquals("idKey=key=<key v=\"0 \"/> nodeId = -30 db=null deletedKeys=null dupKey=<key v=\"<null>\"/>", string0);
  }
}
