/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 21 19:38:09 KST 2017
 */

package com.sleepycat.je;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class TransactionStats_ESTest7 extends TransactionStats_ESTest_scaffolding7 {

  @Test
  public void test00()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      transactionStats0.setNXAPrepares(1523);
      int int0 = transactionStats0.getNXAPrepares();
      assertEquals(1523, int0);
  }

  @Test
  public void test01()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      transactionStats0.setNXAPrepares((-444));
      int int0 = transactionStats0.getNXAPrepares();
      assertEquals((-444), int0);
  }

  @Test
  public void test02()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      transactionStats0.setNXACommits(2157);
      int int0 = transactionStats0.getNXACommits();
      assertEquals(2157, int0);
  }

  @Test
  public void test03()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      transactionStats0.setNXACommits((-674));
      int int0 = transactionStats0.getNXACommits();
      assertEquals((-674), int0);
  }

  @Test
  public void test04()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      transactionStats0.setNXAAborts((-1));
      int int0 = transactionStats0.getNXAAborts();
      assertEquals((-1), int0);
  }

  @Test
  public void test05()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      transactionStats0.setNCommits(466);
      int int0 = transactionStats0.getNCommits();
      assertEquals(466, int0);
  }

  @Test
  public void test06()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      transactionStats0.setNCommits((-1));
      int int0 = transactionStats0.getNCommits();
      assertEquals((-1), int0);
  }

  @Test
  public void test07()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      transactionStats0.setNBegins(1784);
      int int0 = transactionStats0.getNBegins();
      assertEquals(1784, int0);
  }

  @Test
  public void test08()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      transactionStats0.setNBegins((-1));
      int int0 = transactionStats0.getNBegins();
      assertEquals((-1), int0);
  }

  @Test
  public void test09()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      transactionStats0.setNActive(1053);
      int int0 = transactionStats0.getNActive();
      assertEquals(1053, int0);
  }

  @Test
  public void test10()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      transactionStats0.setNActive((-1));
      int int0 = transactionStats0.getNActive();
      assertEquals((-1), int0);
  }

  @Test
  public void test11()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      transactionStats0.setNAborts(750);
      int int0 = transactionStats0.getNAborts();
      assertEquals(750, int0);
  }

  @Test
  public void test12()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      transactionStats0.setNAborts((-1795));
      int int0 = transactionStats0.getNAborts();
      assertEquals((-1795), int0);
  }

  @Test
  public void test13()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      transactionStats0.setLastTxnId((-148L));
      long long0 = transactionStats0.getLastTxnId();
      assertEquals((-148L), long0);
  }

  @Test
  public void test14()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      transactionStats0.setLastCheckpointTime(1270L);
      long long0 = transactionStats0.getLastCheckpointTime();
      assertEquals(1270L, long0);
  }

  @Test
  public void test15()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      transactionStats0.setLastCheckpointTime((-4350L));
      long long0 = transactionStats0.getLastCheckpointTime();
      assertEquals((-4350L), long0);
  }

  @Test
  public void test16()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      TransactionStats.Active[] transactionStats_ActiveArray0 = new TransactionStats.Active[6];
      transactionStats0.setActiveTxns(transactionStats_ActiveArray0);
      TransactionStats.Active[] transactionStats_ActiveArray1 = transactionStats0.getActiveTxns();
      assertSame(transactionStats_ActiveArray1, transactionStats_ActiveArray0);
  }

  @Test
  public void test17()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      TransactionStats.Active[] transactionStats_ActiveArray0 = new TransactionStats.Active[0];
      transactionStats0.setActiveTxns(transactionStats_ActiveArray0);
      TransactionStats.Active[] transactionStats_ActiveArray1 = transactionStats0.getActiveTxns();
      assertSame(transactionStats_ActiveArray1, transactionStats_ActiveArray0);
  }

  @Test
  public void test18()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      TransactionStats.Active[] transactionStats_ActiveArray0 = new TransactionStats.Active[2];
      transactionStats0.setActiveTxns(transactionStats_ActiveArray0);
      String string0 = transactionStats0.toString();
      assertEquals("nBegins=0\nnAborts=0\nnCommits=0\nnXAPrepares=0\nnXAAborts=0\nnXACommits=0\nnActive=0\nactiveTxns=[  null\n  null\n]\nlastTxnId=0\nlastCheckpointTime=Thu Jan 01 09:00:00 KST 1970\n", string0);
  }

  @Test
  public void test19()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      String string0 = transactionStats0.toString();
      assertEquals("nBegins=0\nnAborts=0\nnCommits=0\nnXAPrepares=0\nnXAAborts=0\nnXACommits=0\nnActive=0\nactiveTxns=[]\nlastTxnId=0\nlastCheckpointTime=Thu Jan 01 09:00:00 KST 1970\n", string0);
  }

  @Test
  public void test20()  throws Throwable  {
      TransactionStats.Active transactionStats_Active0 = new TransactionStats.Active("iAoxp.Ga@yOEGNP", 0L, (long) 529);
      long long0 = transactionStats_Active0.getParentId();
      assertEquals(0L, transactionStats_Active0.getId());
      assertEquals(529L, long0);
  }

  @Test
  public void test21()  throws Throwable  {
      TransactionStats.Active transactionStats_Active0 = new TransactionStats.Active("", 0L, 0L);
      long long0 = transactionStats_Active0.getId();
      assertEquals(0L, long0);
  }

  @Test
  public void test22()  throws Throwable  {
      TransactionStats.Active transactionStats_Active0 = new TransactionStats.Active("iAoxp.Ga@yOEGNP", 0L, (long) 529);
      String string0 = transactionStats_Active0.toString();
      assertEquals("txnId = 0 txnName = iAoxp.Ga@yOEGNP", string0);
      assertEquals(529L, transactionStats_Active0.getParentId());
  }

  @Test
  public void test23()  throws Throwable  {
      TransactionStats.Active transactionStats_Active0 = new TransactionStats.Active("%[LR4R1ipYn`*x6t/", 258L, 258L);
      transactionStats_Active0.getName();
      assertEquals(258L, transactionStats_Active0.getId());
      assertEquals(258L, transactionStats_Active0.getParentId());
  }

  @Test
  public void test24()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      int int0 = transactionStats0.getNBegins();
      assertEquals(0, int0);
  }

  @Test
  public void test25()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      long long0 = transactionStats0.getLastCheckpointTime();
      assertEquals(0L, long0);
  }

  @Test
  public void test26()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      int int0 = transactionStats0.getNAborts();
      assertEquals(0, int0);
  }

  @Test
  public void test27()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      transactionStats0.setLastTxnId(1L);
      long long0 = transactionStats0.getLastTxnId();
      assertEquals(1L, long0);
  }

  @Test
  public void test28()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      int int0 = transactionStats0.getNXAAborts();
      assertEquals(0, int0);
  }

  @Test
  public void test29()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      long long0 = transactionStats0.getLastTxnId();
      assertEquals(0L, long0);
  }

  @Test
  public void test30()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      transactionStats0.setNXAAborts(1);
      int int0 = transactionStats0.getNXAAborts();
      assertEquals(1, int0);
  }

  @Test
  public void test31()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      int int0 = transactionStats0.getNXAPrepares();
      assertEquals(0, int0);
  }

  @Test
  public void test32()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      TransactionStats.Active[] transactionStats_ActiveArray0 = transactionStats0.getActiveTxns();
      assertNull(transactionStats_ActiveArray0);
  }

  @Test
  public void test33()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      int int0 = transactionStats0.getNXACommits();
      assertEquals(0, int0);
  }

  @Test
  public void test34()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      int int0 = transactionStats0.getNActive();
      assertEquals(0, int0);
  }

  @Test
  public void test35()  throws Throwable  {
      TransactionStats transactionStats0 = new TransactionStats();
      int int0 = transactionStats0.getNCommits();
      assertEquals(0, int0);
  }
}
