/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 22 00:47:22 KST 2017
 */

package com.sleepycat.je.log;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.sleepycat.je.log.FileHandle;
import com.sleepycat.je.log.FileHandleSource;
import com.sleepycat.je.log.FileManager;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class FileHandleSource_ESTest2 extends FileHandleSource_ESTest_scaffolding2 {

}
