/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 21 22:17:55 KST 2017
 */

package com.sleepycat.je.utilint;

import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import com.sleepycat.je.dbi.EnvironmentImpl;
import com.sleepycat.je.incomp.INCompressor;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class DaemonThread_ESTest7 extends DaemonThread_ESTest_scaffolding7 {

  @Test
  public void test0()  throws Throwable  {
      INCompressor iNCompressor0 = null;
      try {
        iNCompressor0 = new INCompressor((EnvironmentImpl) null, (-24L), "JJim8I8M+1?7^Jq");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.sleepycat.je.incomp.INCompressor", e);
      }
  }
}
