/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 22 01:11:02 KST 2017
 */

package com.sleepycat.je.log;

import static org.junit.Assert.assertFalse;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class LogException_ESTest6 extends LogException_ESTest_scaffolding6 {

  @Test
  public void test0()  throws Throwable  {
      LogException logException0 = new LogException("");
      LogException logException1 = new LogException("vsF 1i;h", (Exception) logException0);
      assertFalse(logException1.equals((Object)logException0));
  }
}
