/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 21 19:33:53 KST 2017
 */

package com.sleepycat.je;

import static org.junit.Assert.assertEquals;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class SequenceConfig_ESTest7 extends SequenceConfig_ESTest_scaffolding7 {

  @Test
  public void test00()  throws Throwable  {
      SequenceConfig sequenceConfig0 = new SequenceConfig();
      long long0 = sequenceConfig0.getRangeMax();
      assertEquals(0L, sequenceConfig0.getInitialValue());
      assertEquals(9223372036854775807L, long0);
      assertEquals((-9223372036854775808L), sequenceConfig0.getRangeMin());
      assertEquals(0, sequenceConfig0.getCacheSize());
  }

  @Test
  public void test01()  throws Throwable  {
      SequenceConfig sequenceConfig0 = new SequenceConfig();
      long long0 = sequenceConfig0.getInitialValue();
      assertEquals(0, sequenceConfig0.getCacheSize());
      assertEquals((-9223372036854775808L), sequenceConfig0.getRangeMin());
      assertEquals(0L, long0);
      assertEquals(9223372036854775807L, sequenceConfig0.getRangeMax());
  }

  @Test
  public void test02()  throws Throwable  {
      SequenceConfig sequenceConfig0 = SequenceConfig.DEFAULT;
      sequenceConfig0.setWrap(true);
      sequenceConfig0.setAutoCommitNoSync(false);
      sequenceConfig0.setAutoCommitNoSync(false);
      int int0 = sequenceConfig0.getCacheSize();
      //  // Unstable assertion: assertEquals(0, int0);
      
      sequenceConfig0.setInitialValue((-703));
      sequenceConfig0.setExclusiveCreate(true);
      sequenceConfig0.setRange((-703), (-703));
      sequenceConfig0.getWrap();
      sequenceConfig0.setInitialValue((-1451L));
      sequenceConfig0.getAutoCommitNoSync();
      sequenceConfig0.setCacheSize((-703));
      sequenceConfig0.getDecrement();
      sequenceConfig0.setAllowCreate(true);
      sequenceConfig0.setDecrement(false);
      sequenceConfig0.getRangeMin();
      long long0 = sequenceConfig0.getInitialValue();
      //  // Unstable assertion: assertEquals((-1451L), long0);
  }

  @Test
  public void test03()  throws Throwable  {
      SequenceConfig sequenceConfig0 = new SequenceConfig();
      int int0 = sequenceConfig0.getCacheSize();
      assertEquals((-9223372036854775808L), sequenceConfig0.getRangeMin());
      assertEquals(9223372036854775807L, sequenceConfig0.getRangeMax());
      assertEquals(0, int0);
      assertEquals(0L, sequenceConfig0.getInitialValue());
  }

  @Test
  public void test04()  throws Throwable  {
      SequenceConfig sequenceConfig0 = SequenceConfig.DEFAULT;
      //  // Unstable assertion: assertEquals(9223372036854775807L, sequenceConfig0.getRangeMax());
      
      sequenceConfig0.setRange(0L, (-133L));
      //  // Unstable assertion: assertEquals((-133L), sequenceConfig0.getRangeMax());
  }

  @Test
  public void test05()  throws Throwable  {
      SequenceConfig sequenceConfig0 = SequenceConfig.DEFAULT;
      boolean boolean0 = sequenceConfig0.getAllowCreate();
      //  // Unstable assertion: assertFalse(boolean0);
  }

  @Test
  public void test06()  throws Throwable  {
      SequenceConfig sequenceConfig0 = SequenceConfig.DEFAULT;
      boolean boolean0 = sequenceConfig0.getExclusiveCreate();
      //  // Unstable assertion: assertFalse(boolean0);
  }

  @Test
  public void test07()  throws Throwable  {
      SequenceConfig sequenceConfig0 = new SequenceConfig();
      sequenceConfig0.getWrap();
      assertEquals(0L, sequenceConfig0.getInitialValue());
      assertEquals((-9223372036854775808L), sequenceConfig0.getRangeMin());
      assertEquals(0, sequenceConfig0.getCacheSize());
      assertEquals(9223372036854775807L, sequenceConfig0.getRangeMax());
  }

  @Test
  public void test08()  throws Throwable  {
      SequenceConfig sequenceConfig0 = SequenceConfig.DEFAULT;
      long long0 = sequenceConfig0.getRangeMax();
      //  // Unstable assertion: assertEquals(9223372036854775807L, long0);
  }

  @Test
  public void test09()  throws Throwable  {
      SequenceConfig sequenceConfig0 = SequenceConfig.DEFAULT;
      long long0 = sequenceConfig0.getRangeMin();
      //  // Unstable assertion: assertEquals((-9223372036854775808L), long0);
  }

  @Test
  public void test10()  throws Throwable  {
      SequenceConfig sequenceConfig0 = SequenceConfig.DEFAULT;
      int int0 = sequenceConfig0.getCacheSize();
      //  // Unstable assertion: assertEquals(0, int0);
  }
}
