/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 21 23:57:08 KST 2017
 */

package com.sleepycat.je.cleaner;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.sleepycat.je.cleaner.TrackedFileSummary;
import com.sleepycat.je.cleaner.UtilizationProfile;
import com.sleepycat.je.cleaner.UtilizationTracker;
import com.sleepycat.je.dbi.EnvironmentImpl;
import java.io.File;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class UtilizationProfile_ESTest6 extends UtilizationProfile_ESTest_scaffolding6 {

  @Test
  public void test00()  throws Throwable  {
      int int0 = UtilizationProfile.utilization(0L, 1000000L);
      assertEquals(100, int0);
  }

  @Test
  public void test01()  throws Throwable  {
      UtilizationProfile.UtilizationProfile_putFileSummary utilizationProfile_UtilizationProfile_putFileSummary0 = new UtilizationProfile.UtilizationProfile_putFileSummary((UtilizationProfile) null, (TrackedFileSummary) null);
      File file0 = null;
      try {  
      file0 = utilizationProfile_UtilizationProfile_putFileSummary0.file;
      } catch(NullPointerException e) {}
  }

  @Test
  public void test02()  throws Throwable  {
      UtilizationProfile.UtilizationProfile_putFileSummary utilizationProfile_UtilizationProfile_putFileSummary0 = new UtilizationProfile.UtilizationProfile_putFileSummary((UtilizationProfile) null, (TrackedFileSummary) null);
      // Undeclared exception!
      try { 
        utilizationProfile_UtilizationProfile_putFileSummary0.execute();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.sleepycat.je.cleaner.UtilizationProfile", e);
      }
  }

  @Test
  public void test03()  throws Throwable  {
      UtilizationProfile.UtilizationProfile_populateCache utilizationProfile_UtilizationProfile_populateCache0 = new UtilizationProfile.UtilizationProfile_populateCache((UtilizationProfile) null);
      // Undeclared exception!
      try { 
        utilizationProfile_UtilizationProfile_populateCache0.execute();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.sleepycat.je.cleaner.UtilizationProfile", e);
      }
  }

  @Test
  public void test04()  throws Throwable  {
      int int0 = UtilizationProfile.utilization((-3244L), (-1L));
      assertEquals((-324300), int0);
  }

  @Test
  public void test05()  throws Throwable  {
      int int0 = UtilizationProfile.utilization(0L, 0L);
      assertEquals(0, int0);
  }

  @Test
  public void test06()  throws Throwable  {
      UtilizationProfile.UtilizationProfile_clearCache utilizationProfile_UtilizationProfile_clearCache0 = new UtilizationProfile.UtilizationProfile_clearCache((UtilizationProfile) null);
      // Undeclared exception!
      try { 
        utilizationProfile_UtilizationProfile_clearCache0.execute();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.sleepycat.je.cleaner.UtilizationProfile", e);
      }
  }

  @Test
  public void test11()  throws Throwable  {
      UtilizationProfile.UtilizationProfile_populateCache utilizationProfile_UtilizationProfile_populateCache0 = new UtilizationProfile.UtilizationProfile_populateCache((UtilizationProfile) null);
      utilizationProfile_UtilizationProfile_populateCache0.hook176();
  }

  @Test
  public void test16()  throws Throwable  {
      UtilizationProfile utilizationProfile0 = null;
      try {
        utilizationProfile0 = new UtilizationProfile((EnvironmentImpl) null, (UtilizationTracker) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.sleepycat.je.cleaner.UtilizationProfile", e);
      }
  }

  @Test
  public void test19()  throws Throwable  {
      Long long0 = new Long((long) 20);
      UtilizationProfile.UtilizationProfile_removeFile utilizationProfile_UtilizationProfile_removeFile0 = new UtilizationProfile.UtilizationProfile_removeFile((UtilizationProfile) null, long0);
      // Undeclared exception!
      try { 
        utilizationProfile_UtilizationProfile_removeFile0.execute();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.sleepycat.je.cleaner.UtilizationProfile$UtilizationProfile_removeFile", e);
      }
  }
}
