/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 22 13:21:44 KST 2017
 */

package com.sleepycat.bind.tuple;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.sleepycat.bind.tuple.TupleInput;
import com.sleepycat.bind.tuple.TupleInputBinding;
import com.sleepycat.je.DatabaseEntry;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class TupleInputBinding_ESTest4 extends TupleInputBinding_ESTest_scaffolding4 {

  @Test
  public void test0()  throws Throwable  {
      TupleInputBinding tupleInputBinding0 = new TupleInputBinding();
      DatabaseEntry databaseEntry0 = new DatabaseEntry();
      byte[] byteArray0 = new byte[3];
      TupleInput tupleInput0 = new TupleInput(byteArray0);
      tupleInputBinding0.objectToEntry(tupleInput0, databaseEntry0);
      assertTrue(tupleInput0.markSupported());
  }




  @Test
  public void test4()  throws Throwable  {
      TupleInputBinding tupleInputBinding0 = new TupleInputBinding();
      DatabaseEntry databaseEntry0 = new DatabaseEntry();
      TupleInput tupleInput0 = (TupleInput)tupleInputBinding0.entryToObject(databaseEntry0);
      assertEquals(0, tupleInput0.getBufferOffset());
  }
}
